const PdfParse=require("pdf-parse");
const {generateInterviewReport, generateResumePdf}=require("../services/AI_service");
const interviewModel=require("../models/InterviewModel");

/**
 * @description Controller to generate interview report based on user self description, resume and job description.
 */

async function generateInterviewReportController(req,res){
    const resume_content=await (new PdfParse.PDFParse(Uint8Array.from(req.file.buffer))).getText();
    const {selfDescription, jobDescription}=req.body;

    const interview_report_ai=await generateInterviewReport({
        resume:resume_content.text,
        selfDescription,
        jobDescription
    })

    const interview_report_db=await interviewModel.create({
        user:req.user.id,
        resume:resume_content.text,
        selfDescription,
        jobDescription,
        ...interview_report_ai,//spreading the interview report generated by AI into the database document so it can be stored in the database
        title:interview_report_ai.title || "Untitled Position"//fallback in case the AI response omits the title
    });

    res.status(201).json({
        message:"Interview report generated successfully",
        interviewReport:interview_report_db
    });
}

/**
 * @description Controller to get interview report by interviewId.
 */

async function getInterviewReportById(req,res){
    const {interviewId}=req.params;
    const interview_report=await interviewModel.findOne({ _id: interviewId, user: req.user.id });
    
    if(!interview_report){
        return res.status(404).json({
            message:"Interview report not found"
        });
    }

    res.status(200).json({
        message:"Interview report fetched successfully",
        interviewReport:interview_report
    });
}

/** 
 * @description Controller to get all interview reports of logged in user.
 */

async function getAllInterviewReports(req,res){
    const interview_reports=await interviewModel.find({ user:req.user.id }).sort({ createdAt: -1 })
            .select("-resume -selfDescription -jobDescription -__v -technicalQuestions -behavioralQuestions -skillGaps -preparationPlan");//excluding the fields that are not needed in the response

    res.status(200).json({
        message:"Interview reports fetched successfully",
        interviewReports:interview_reports
    });
}


/**
 * @description Controller to generate resume PDF based on user self description, resume and job description.
 */
async function generateResumePdfController(req, res) {
    const { interviewReportId } = req.params

    const interviewReport = await interviewModel.findById(interviewReportId)

    if (!interviewReport) {
        return res.status(404).json({
            message: "Interview report not found."
        })
    }

    const { resume, jobDescription, selfDescription } = interviewReport

    const pdfBuffer = await generateResumePdf({ resume, jobDescription, selfDescription })

    res.set({
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename=resume_${interviewReportId}.pdf`
    })

    res.send(pdfBuffer)
}

module.exports={generateInterviewReportController, getInterviewReportById, getAllInterviewReports, generateResumePdfController}
